apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: init-iptables
          image: gcr.io/celi12/iptables-setup:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          command:
            - sh
            - -c
            - |
              iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-port 10000 && \
              iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to-port 10000
      containers:
        - name: backend
          image: gcr.io/celi12/backend-image:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /api/home
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/home
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 10
        - name: envoy-sidecar
          image: gcr.io/celi12/envoy-image:latest
          ports:
            - containerPort: 10000
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config-backend
