apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config-backend
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: backend_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: backend
                    codec_type: AUTO
                    route_config:
                      virtual_hosts:
                        - name: backend
                          domains: ["*"]
                          routes:
                            - match: { prefix: "/" }
                              route: { cluster: backend_service }
                    http_filters:
                      - name: envoy.filters.http.lua
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                          inline_code: |
                            function envoy_on_request(request_handle)
                                local headers = request_handle:headers()
                                local body_handle = request_handle:body()
                                local body = ""

                                if body_handle then
                                    body = body_handle:getBytes(0, body_handle:length()) or ""
                                end

                                local request_info = {
                                    type = "request",
                                    method = headers:get(":method") or "UNKNOWN",
                                    path = headers:get(":path") or "UNKNOWN",
                                    headers = {},
                                    body = body
                                }

                                -- Capture all request headers
                                for key, value in pairs(headers) do
                                    request_info.headers[key] = value
                                end

                                request_handle:logInfo(require("cjson").encode(request_info))
                            end

                            function envoy_on_response(response_handle)
                                local headers = response_handle:headers()
                                local body_handle = response_handle:body()
                                local body = ""

                                if body_handle then
                                    body = body_handle:getBytes(0, body_handle:length()) or ""
                                end

                                local response_info = {
                                    type = "response",
                                    status = headers:get(":status") or "UNKNOWN",
                                    headers = {},
                                    body = body
                                }

                                -- Capture all response headers
                                for key, value in pairs(headers) do
                                    response_info.headers[key] = value
                                end

                                response_handle:logInfo(require("cjson").encode(response_info))
                            end


                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
        - name: backend_service
          connect_timeout: 5s
          type: LOGICAL_DNS
          load_assignment:
            cluster_name: backend_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: backend-service
                          port_value: 80
