apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: gcr.io/celi12/ui-image:latest
          ports:
            - containerPort: 80
        - name: envoy
          image: envoyproxy/envoy:v1.27.0
          ports:
            - containerPort: 15000  # Envoy Admin UI
            - containerPort: 10000  # Proxy Port
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config-ui
